// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDit_YY7OfsiUVenzQ3xwniokorIa1oRO4',
    appId: '1:777824953279:web:e7f6603260de49a7cef70a',
    messagingSenderId: '777824953279',
    projectId: 'todo-list-provider-614d1',
    authDomain: 'todo-list-provider-614d1.firebaseapp.com',
    storageBucket: 'todo-list-provider-614d1.appspot.com',
    measurementId: 'G-HL6PSR2RTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Yz0f7ii_anWqhz1TVTSOHHPUz9qxyyY',
    appId: '1:777824953279:android:62544c3492d12231cef70a',
    messagingSenderId: '777824953279',
    projectId: 'todo-list-provider-614d1',
    storageBucket: 'todo-list-provider-614d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS3YZQGcTThmZ5X014ksT6n5LWF8vvask',
    appId: '1:777824953279:ios:3fc472558d157550cef70a',
    messagingSenderId: '777824953279',
    projectId: 'todo-list-provider-614d1',
    storageBucket: 'todo-list-provider-614d1.appspot.com',
    androidClientId: '777824953279-iul09p0r7imukhcml52f7t3n3chen846.apps.googleusercontent.com',
    iosClientId: '777824953279-tg0qbo3jmam7c8sk87j6a4qs7pubk49i.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS3YZQGcTThmZ5X014ksT6n5LWF8vvask',
    appId: '1:777824953279:ios:5421e267e169f6cfcef70a',
    messagingSenderId: '777824953279',
    projectId: 'todo-list-provider-614d1',
    storageBucket: 'todo-list-provider-614d1.appspot.com',
    androidClientId: '777824953279-iul09p0r7imukhcml52f7t3n3chen846.apps.googleusercontent.com',
    iosClientId: '777824953279-n3h25ogeo2svm9vrp6tmukup8bvdnegi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProvider.RunnerTests',
  );
}
